# Generated by Django 5.1.7 on 2025-08-15 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(choices=[('arkanoid', 'Арканоид'), ('tetris', 'Тетрис'), ('snake', 'Змейка'), ('space_shooter', 'Космический шутер'), ('flappy_bird', 'Flappy Bird'), ('ping_pong', 'Пинг-понг'), ('coinrunner', 'Coin Runner'), ('runner', 'Бегун'), ('labyrint', 'Лабиринт'), ('base_defender', 'Защита базы')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Score',
                'verbose_name_plural': 'Game Scores',
                'ordering': ['-score', 'achieved_at'],
            },
        ),
    ]
