# Generated by Django 5.1.7 on 2025-08-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(choices=[('arkanoid', 'Арканоид'), ('tetris', 'Тетрис'), ('snake', 'Змейка'), ('space_shooter', 'Космический шутер'), ('flappy_bird', 'Flappy Bird'), ('ping_pong', 'Пинг-понг'), ('coinrunner', 'Coin Runner'), ('runner', 'Бегун'), ('labyrint', 'Лабиринт'), ('base_defender', 'Защита базы')], max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Comment',
                'verbose_name_plural': 'Game Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
