# Generated by Django 5.1.7 on 2025-09-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='game_name',
            field=models.CharField(choices=[('arkanoid', 'Арканоїд'), ('tetris', 'Тетріс'), ('snake', 'Змійка'), ('space_shooter', 'Космічний шутер'), ('flappy_bird', 'Flappy Bird'), ('ping_pong', 'Пінг-понг'), ('coinrunner', 'Coin Runner'), ('runner', 'Бігун'), ('labyrint', 'Лабіринт'), ('base_defender', 'Захист бази')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game_name',
            field=models.CharField(choices=[('arkanoid', 'Арканоїд'), ('tetris', 'Тетріс'), ('snake', 'Змійка'), ('space_shooter', 'Космічний шутер'), ('flappy_bird', 'Flappy Bird'), ('ping_pong', 'Пінг-понг'), ('coinrunner', 'Coin Runner'), ('runner', 'Бігун'), ('labyrint', 'Лабіринт'), ('base_defender', 'Захист бази')], max_length=20),
        ),
    ]
